
services:
  postgres:
    image: postgres:15-alpine
    container_name: strava_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: strava_runner
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - strava_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: strava_backend
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/strava_runner?schema=public
      STRAVA_CLIENT_ID: ${STRAVA_CLIENT_ID}
      STRAVA_CLIENT_SECRET: ${STRAVA_CLIENT_SECRET}
      STRAVA_CALLBACK_URL: ${STRAVA_CALLBACK_URL:-http://localhost:3001/auth/strava/callback}
      JWT_SECRET: ${JWT_SECRET}
      PORT: 3001
      NODE_ENV: production
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:5173}
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - strava_network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: strava_frontend
    restart: always
    environment:
      VITE_API_URL: http://localhost:3001
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - strava_network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  strava_network:
    driver: bridge
